name: Stable Release

on:
  push:
    branches:
      - master

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test
      - name: Build
        run: docker build -t release .
      - name: Publish
        # To make this actually run, add -w yes
        run: > 
          docker run 
          --env GH_TOKEN="${{ secrets.MERGESAT_GITHUB_TOKEN }}"
          --env CARGO_TOKEN="${{ secrets.CARGO_TOKEN }}" 
          --env GIT_COMMITTER_NAME="Najib Ishaq"
          --env GIT_COMMITTER_EMAIL="najib_ishaq@zoho.com"
          release /bin/bash -c "cargo install semantic-rs && semantic-rs"
